./buildAndCopy.sh 134-deposit-in
./buildAndCopy.sh 134-deposit-ongoing
./buildAndCopy.sh 134-deposit-request
./buildAndCopy.sh 134-email-verify
./buildAndCopy.sh 134-login-notify
./buildAndCopy.sh 134-usdt-deposit-success
./buildAndCopy.sh 134-usdt-withdraw-approve
./buildAndCopy.sh 134-withdraw-finish
./buildAndCopy.sh 134-withdraw-ongoing
./buildAndCopy.sh 134-withdraw-request
